In [8]:
import tensorflow as tf
import numpy as np

In [9]:
np.set_printoptions(precision=3)
a = np.array([1,2,3], dtype=np.int32)
b = [4,5,6]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
print(t_a, t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [11]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5,2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5,2), mean=0.0, stddev=1.0)
print(t1, t2)

tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32) tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)


In [18]:
ds = tf.data.Dataset.from_tensor_slices(t1)
print(ds)
for i , elem in enumerate(ds.batch(2), 1):
    print('batch {}: {}.'.format(i, elem.numpy()))

<TensorSliceDataset shapes: (2,), types: tf.float32>
batch 1: [[-0.67   0.803]
 [ 0.262 -0.131]].
batch 2: [[-0.416  0.285]
 [ 0.952 -0.13 ]].
batch 3: [[0.32 0.21]].
